# Generated by Django 4.2.3 on 2023-07-08 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="rate",
            field=models.PositiveSmallIntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
