name: Build and Push Docker Image to Docker Hub
on:
  push:
    branches: ["main", "imp-deploy-github_action"]
  pull_request:
    branches:  ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run : cp sample.env .env
      - name: build the docker Image
        run: docker-compose build --no-cache --force-rm
  
  test:
    name: check docker image health
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: test docker image
        run: docker-compose up
    
  deploy:
    runs-on: ubuntu
    name: push docker image to docker registry(docker hub)
    steps:
      - uses: actions/checkout@v3

      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

